### ISSUE TITLE
Default key exchange parameters are insecure.

### ISSUE THREAD

**Issue by micklh** [erose1337/epqcrypto#1]
The "EPQ" key exchange program given here is vulnerable to a Lagarias-Odlyzko style lattice attack. The usual upper triangular lattice basis matrix is formed by taking an identity matrix and replacing the rightmost column with a vector made from the public key, system parameters, and ciphertext. This 3 dimensional lattice contains a short vector that exposes the plaintext, allowing us to recover it with an SVP oracle.

I've experimentally verified the attack using fpLLL as the SVP oracle, and had successful key recovery in every trial. For concreteness and convenience, the lattice basis I've used is (where `P` is the system modulus, `K` is the public key, and `C` is the ciphertext):
```
[1 0 P]
[0 1 K]
[0 0 C]
```

**Comment by erose1337** [comment]
Is there any chance you could share your implementation of the attack? I would ideally prefer to see it in python, but I know you don't write in python by default and I have no idea what the implementation complexity is.

When you say that the parameters are insecure, does this mean there exist parameter selections that do not fall to the attack you are presenting here? 

I appreciate you going out of your way to apply hands-on analysis and opening a ticket - thanks!

**Comment by micklh** [comment]
I actually used vanilla [fpLLL](https://github.com/fplll/fplll) on the command line, and manually typed in the numbers generated by the program. To demonstrate, I've generated this keypair just now:
```
Public: 914984079037409997753646956896411367020716296641338957641608068567317657086975832590795630339277510788727851945111403187181412830140879040014025475367233381190196941804342169193880920240279264797993403702890997094738006766532630568999

Private: 2502644320274784300686027905786577204651695824856428916800576785188468831099194056968432976701679611038222704877942453351051289674522482331865454722815092306
```

And encrypted a random key to get this ciphertext: `31156599101993645275226400017248608173867507193910625562695392661378570296553738808446028840212848623662312900007512235634449530713883849145685393866636831069585880990434485646285032107701202733953935100342846543008476824530843873800801`.
(The random key was: `101020355786439301914818388108389342468906297672328361246394394849844032365586`)

Then I entered this into the command line by hand (the flag `-a svp` tells fpLLL to act as an SVP oracle):
```
mick@mick-desktop:~$ ~/codes/fplll/fplll/fplll -a svp
[[1 0 90539821999601667010016498433538092350601848065509335050382778168697877622963864208930434463149476126948597274673237394102007067278620641565896411613073030816577188842779580374266789048335983054644275218968175557708746520394332802669663]
[0 1 914984079037409997753646956896411367020716296641338957641608068567317657086975832590795630339277510788727851945111403187181412830140879040014025475367233381190196941804342169193880920240279264797993403702890997094738006766532630568999]
[0 0 31156599101993645275226400017248608173867507193910625562695392661378570296553738808446028840212848623662312900007512235634449530713883849145685393866636831069585880990434485646285032107701202733953935100342846543008476824530843873800801]]
```

fpLLL short vector output:
```
[203453603089198469384658317783196545918051882397653184390372945748471804449 -20132211511540947010614907531449286044959891949349819581130241666199997596098 101020355786439301914818388108389342468906297672328361246394394849844032365586]
```
Which is of the form `[-modular_reduction_value, -s_value, plaintext]` which correctly recovers the plaintext `101020355786439301914818388108389342468906297672328361246394394849844032365586` as well as the random `s` value used during encryption.

As for parameters that foil this attack, I found that the lattice starts to contain many unrelated short vectors if either `s` or `e` are increased in size by around 16 bits, but this causes the lower 16 bits of the shared key to be corrupted, and these 16 bits can be searched by brute force. Maybe one possibility would be to increase the size of `s` by 128 bits, at the cost of shortening the shared key by 128 bits?

**Comment by erose1337** [comment]
Ok, so first a quick overview:

```
a_i(a r s + e) == r s + a_i e mod P
````

So for the algorithm to function correctly, we require that `a_i > r s` and `a_i e < P`.
I have this formula for calculating parameter sizes:

```    
short_inverse_size = (security_level * 2) + 1
p_size = short_inverse_size + security_level + 1
return short_inverse_size, security_level, security_level, security_level, p_size```

The sizes given here are in bytes. I chose the original parameter sizes by selecting 32 bytes as the basic security level, and using that for all parameters other then `P`, which is determined by the rest of the sizes that we want to use. I selected these values because I did not know of a better attack then brute force at the time.

To facilitate an increase of the size of `e` by 16 bits, we would simply make `P` 16 bits larger. 
To facilitate an increase of the size of `s` by 16 bits, we would need to make `a_i` larger, as well as make `P` 16 bits larger to compensate for the larger `a_i`.

It appears that we could increase the size of `s` by more or less any amount at the cost of increasing the size of `a_i` and/or shrinking the value `e`. If we simply make `P` 16 bits larger so that we can make `e` 16 bits larger, it would be simple, but it might not actually fix anything - the larger modulus size might move the goal post for how large `e` needs to be (or it might not).

So I guess the real question is, what are the optimal parameter choices in regards to efficiency? For example, we could set `e` to be 1 bit in size, but then it would become massively inefficient. So it looks like we want `e` to be as large as we can manage?

**Comment by micklh** [comment]
That's the "gotcha", if you also scale the rest of the parameters, it effectively scales the short vectors of the lattice to match. All the modifications that thwarted the attack also corrupted some number of LSBs of the shared key, such that the number of corrupt bits was also an upper bound to the amount of effort required to recover the key.

**Comment by erose1337** [comment]
How does the difficulty scale with additional points for the public key/public key operation? As in:

```
ciphertext = a r_1 s_1 + a r_2 s_2 + e
```

Where `a r_1, a r_2` is now the public key

I guess I will implement it and then you can simply tell me if it still breaks.

**Comment by erose1337** [comment]
I implemented it; the current version uses two points in the public key, instead of just one.

**Comment by micklh** [comment]
I think that should kill this attack by making the target vector longer than the short vectors found during lattice reduction. 

This is just a feeling, but I think if you use enough "points" you'll eventually have an `s` vector with large enough min-entropy to apply the leftover hash lemma and get a nice proof that the ciphertext is statistically uniform. Though with that said, I haven't given the private key to public key relationship enough cryptanalysis to say whether or not that strategy is workable for the overall system.

**Comment by erose1337** [comment]
I think the number of points could be increased by a good margin still, if need be; A public key could probably consist of a few hundred points before the decryption operation will fail. Basically, with fewer points, the keys are smaller and the keygen time/public key operation is faster, so I am trying to operate in the smallest dimension that I can get away with.

**Comment by micklh** [comment]
I think the LHL will ask you for maybe 5-ish

**Comment by erose1337** [comment]
With this modification, is it secure to use non-random values for `e`? i.e. `e = 0`

**Comment by micklh** [comment]
Ok, so keep in mind this argument only applies when we're pretending the public key vector is uniformly random mod P. An inner product with a uniform random vector mod P is a universal hash function family. In this context, the public key is the seed that determines the random member `H(...)` of the family. Let `X` be a random variable with min-entropy `m` (the "s value" used during encryption). Here `v` is the length of the extracted randomness, which is equal to the bit length of P. The Leftover Hash Lemma in essence tells us:
> ...The statistical distance between H(X) and the uniform distribution is bounded by √2^-L,
> where L = m − v...

Usually `L` is called "entropy loss". We can simplify the statistical distance by observing `√2^-L = 2^(-L/2)` so that for a concrete statistical distance of 2^-λ, we find that entropy loss L = 2λ. Now we can find a suitable amount of min-entropy `m` by transforming `m - v = 2λ` into `m = 2λ + v`. Since you said before that P is 3 times the security level (plus a constant), we can substitute `v = 3λ + O(1)` and get `m = 5λ + O(1)`. The distribution of each component of the "s value" is uniform over an interval, so the min-entropy of the vector value is equal to the bit length of each component, times the number of components. Since each component has bit length λ, we need `5 + O(1/λ)` public key "points" to guarantee that the output is 2^-λ statistically close to uniform mod P.

**Comment by micklh** [comment]
In short, 5 points is the magic number where the LHL proof kicks in.

As for:
> With this modification, is it secure to use non-random values for e? i.e. e = 0

Yes, as long as `e` and `s` are independent. The inner product with the "small" random values produces a statistically random value mod P, even before the message is added in at all.

**Comment by erose1337** [comment]
The implementation now defaults to using 5 points in the public key. Sometime today I will make an additional modification to facilitate user-selected `e` values instead of only allowing randomly generated ones.

Thanks for all of your help, it is most appreciated.

**Comment by micklh** [comment]
Sweet. If we assume that the public key is indistinguishable from 5 independent random integers mod P, then the above LHL argument can be made rigorous; however, there is a minor technical issue caused by the public key elements always being odd. A trivial distinguisher can achieve a non-negligible advantage by observing that the probability of 5 random elements being odd is about 2^-5, while the public keys satisfy this property with probability 1. I doubt that such a trivial distinguisher is of any real concern, and I have a hunch that the proof can be adjusted to compensate by viewing the hash function family as ε-almost-universal, but I'm curious; why are the public keys are restricted to odd values?

Just for good measure, I adjusted the attack to these new parameters and experimentally verified that the lattices have `det(L) ~= 2^177`, and contain short vectors with `||v|| ~= 2^64`, which destroys the accuracy of the attack because our target vector has length ~2^257, so it is well hidden among the vast set of unrelated vectors and the attack has almost no chance of finding it. Improving the accuracy by combining the attack with a brute force search increases the runtime by at least 2^1000, so it seems safe to say that it's secure from this attack now. I'll close this issue, though I think it would be worthwhile to rigorously show that the public key is computationally indistinguishable from uniform under some standard assumption, which would complement the above LHL argument and give a very solid security proof.

**Comment by erose1337** [comment]
Oh, that was something that turned out to be unnecessary that I have not yet removed; At the time I was scrutinizing `a r` for some way to predict output bits. From the perspective of the bits during integer multiplication, if `a` has no lower bits set, then `a r` will have no lower bits set as well - Obviously, the modular reduction step diffuses the changes across the rest of the word, and `a r mod P` does not exhibit this same problem. 

I will remove the `| 1` in the code, thank you for pointing it out.

**Comment by erose1337** [comment]
> ...I think it would be worthwhile to rigorously show that the public key is computationally indistinguishable from uniform under some standard assumption, which would complement the above LHL argument and give a very solid security proof.

I think this would be wonderful - However, crafting such proofs is beyond my personal ability. While I am not opposed to learning the requisite skills, it may take me quite some time to do so. If you would like to help with the construction of such a proof, I would greatly appreciate the assistance.

**Comment by micklh** [comment]
I'd be glad to help out with that if I can, and I've got a few performance tweaks I'd like to suggest as well. Is there some instant messenger we could use?

**Comment by erose1337** [comment]
I made a chat room on [crypto.stackexchange](https://chat.stackexchange.com/rooms/62670/epq-key-exchange) about proving the security of the EPQ key exchange function

**Comment by micklh** [comment]
I don't use stack exchange chat because they have made it explicitly clear that they consider their users to be expendable content-writing slaves who deserve absolutely zero compensation for their efforts, and openly support bigotry, censorship, and general intolerance of any opinion differing whatsoever from the point of view of their staff. I've sent you an email instead.
